spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: never
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
